# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming society at UoE
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://progsoc.visgean.me" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Nevim. Only current teaching assistants have the right to stand for the position of new Head of Teaching.

github_link: visgean/progsoc
facebook_link: https://www.facebook.com/groups/314067608963415/
email: your-email@domain.com

# Build settings
markdown: kramdown

theme: minima
